- name: logstash confg file
  ansible.builtin.template:
      src: logstash.conf
      dest: /etc/logstash/conf.d/logstash.conf

- name: logstash service restart
  ansible.builtin.systemd:
      - name: logstash
        state: restarted
        enabled: yes